apiVersion: v1
kind: ReplicationController
metadata:
        name: my-calc-rc
spec:
        replicas: 2
        selector:
                app: my-calc
        template:
                metadata:
                        labels:
                                app: my-calc
                spec:
                        containers:
                                - name: my-calc
                                  image: hidetosaito/my-calc
