apiVersion: v1
kind: Service
metadata:
        name: my-calc-service
spec:
        ports:
                - protocol: TCP
                  port: 5000
        type: ClusterIP
        selector:
                app: my-calc

