apiVersion: v1
kind: ReplicationController
metadata:
        name: my-frontend-rc
spec:
        replicas: 2
        selector:
                app: my-frontend
        template:
                metadata:
                        labels:
                                app: my-frontend
                spec:
                        containers:
                                - name: my-frontend
                                  image: hidetosaito/my-frontend

                        

