apiVersion: v1
kind: Service
metadata:
        name: my-frontend-service
spec:
        ports:
                - protocol: TCP
                  port: 5000
                  nodePort: 30080
        type: NodePort
        selector:
                app: my-frontend
