apiVersion: "v1"
kind: Pod
metadata:
        name: redis
        labels:
                name: redis
                app: demo
spec:
        containers:
                - name: redis
                  image: redis:latest
                  ports:
                          - containerPort: 6739
                            protocol: TCP
